"""Contract-C report rendering helpers.

The primary renderer is the React client.  This module deliberately contains only
dependency-free Markdown and plain-text export functions; presentation widgets belong
in ``web/`` and are not duplicated in Python.
"""

import re
from datetime import date


_DISCLAIMER = {
    "sample": "Illustrative sample - placeholder data, not real facts about any real company.",
    "live": "Built live from public sources; fields not found are unknown, never invented. Not investment advice.",
    "upload": "Built from your uploaded data. Not investment advice.",
    "dataset": "Built from pre-scored local dataset values (not a live fetch); absent fields are unknown. Not investment advice.",
}


def _known(value):
    """Return whether a value is present and not the contract's unknown sentinel."""
    return bool(value) and str(value).strip().lower() != "unknown"


def _disclaimer(company):
    """Return an origin-aware disclaimer without mislabelling local or live data."""
    origin = (company or {}).get("_origin", "sample")
    return _DISCLAIMER.get(origin, "Not investment advice.")


def _card_text(answer, company):
    """Render the Contract C answer as a portable plain-text card."""
    if company:
        subject = (f"{company.get('company', '—')} ({company.get('ticker', '—')}) · "
                   f"{company.get('sector', '—')}")
    else:
        subject = "—"
    lines = [
        f"ASEAN ESG Momentum Radar — {subject}",
        f"({_disclaimer(company)})", "",
        f"VERDICT: {answer.get('competes_summary', 'unknown')}", "",
        f"Question: {answer.get('question_to_ask', 'unknown')}",
        f"What the rating sees: {answer.get('what_rating_sees', 'unknown')}",
        f"What we see: {answer.get('what_we_see', 'unknown')}",
        f"Check before Monday: {answer.get('check_before_monday', 'unknown')}",
    ]
    reasoning = answer.get("reasoning") or []
    if reasoning:
        lines += ["", "Reasoning (chain of thought):"]
        lines += [f"  {i}. {step}" for i, step in enumerate(reasoning, 1)]
    sources = answer.get("sources") or []
    if sources:
        lines += ["", "Sources (live retrieval):"]
        lines += [f"  - {s.get('title') or s.get('url')} {s.get('url', '')}".rstrip()
                  for s in sources]
    return "\n".join(lines) + "\n"


def _card_md(answer, company):
    """Render Contract C as a grounded Markdown report, omitting unknown-only sections."""
    today = date.today().isoformat()
    name = (company or {}).get("company", "—")
    if company:
        subject = f"{name} (`{company.get('ticker', '—')}`) · {company.get('sector', '—')}"
    else:
        subject = "—"
    lines = [
        f"# ASEAN ESG Momentum Radar — {name}",
        f"**{subject}**  ·  _{today}_", f"> _{_disclaimer(company)}_", "", "---", "",
        "## Verdict", f"> {answer.get('competes_summary', 'unknown')}", "", "---", "",
        f"**Question:** {answer.get('question_to_ask', 'unknown')}", "",
        "## Market view vs. reality", "",
        "**What the rating sees**  ", answer.get("what_rating_sees", "unknown"), "",
        "**What we see**  ", answer.get("what_we_see", "unknown"), "", "---", "",
        "## Check before Monday", answer.get("check_before_monday", "unknown"), "",
    ]
    layer_b = (company or {}).get("layer_b") or {}
    momentum = layer_b.get("momentum") or {}
    digital = layer_b.get("digital_ai_signal") or {}
    momentum_rows = []
    for pillar in ("E", "S", "G"):
        data = momentum.get(pillar) or {}
        direction, magnitude = data.get("direction"), data.get("magnitude")
        if _known(direction) or _known(magnitude):
            suffix = f" ({magnitude})" if _known(magnitude) else ""
            momentum_rows.append(f"- **{pillar}**: {direction if _known(direction) else 'unknown'}{suffix}")
    ai_rows = []
    for key, label in (("ai_governance_hiring_velocity", "Digital/AI hiring velocity"),
                       ("ai_disclosure_level", "AI disclosure level")):
        if _known(digital.get(key)):
            ai_rows.append(f"- **{label}**: {digital[key]}")
    if _known(digital.get("gap_note")):
        ai_rows.append(f"  > _{digital['gap_note']}_")
    if momentum_rows or ai_rows:
        lines += ["---", "", "## ESG pillar signals", ""] + momentum_rows + ai_rows + [""]
    reasoning = answer.get("reasoning") or []
    if reasoning:
        lines += ["---", "", "## Chain of thought", ""]
        lines += [f"{i}. {step}" for i, step in enumerate(reasoning, 1)] + [""]
    sources = answer.get("sources") or []
    if sources:
        lines += ["---", "", "## Sources (live retrieval)", ""]
        for source in sources:
            title = source.get("title") or source.get("url") or "source"
            url = source.get("url", "")
            lines.append(f"- [{title}]({url})" if url else f"- {title}")
        lines.append("")
    lines += ["---", "", "_Not investment advice. Generated by ASEAN ESG Momentum Radar._"]
    return "\n".join(lines) + "\n"
