"""Deterministic ILLUSTRATIVE enrichment for demo constituents (HARD RULE 2: labelled, no
fabricated URLs/real facts). Seeded off the company name so the demo is stable across runs."""
import datetime as _dt
import hashlib

_CCY = {"SGX": "SGD", "KLSE": "MYR", "IDX": "IDR", "SET": "THB", "PSE": "PHP", "HOSE": "VND"}


# The demo universe's as-of. A FIXED anchor, never the clock: this file is regenerated by a
# script and committed, and a generator that read today's date would produce a different fixture
# on every run and break the golden set for no reason.
_AS_OF = _dt.date(2026, 6, 30)


def _date_back(days):
    return (_AS_OF - _dt.timedelta(days=int(days))).isoformat()


def _rng(name, salt):
    h = hashlib.md5(f"{name}|{salt}".encode("utf-8")).hexdigest()
    return int(h[:8], 16) / 0x100000000          # 0..1


def _pick(name, salt, lo, hi):
    return lo + (hi - lo) * _rng(name, salt)


def trajectory(name):
    """improving | mixed | deteriorating — one deterministic story per demo company.

    Every enrichment block below reads this, so a company's momentum, live signals and headlines
    tell the SAME story. Without it the demo set was uniformly positive (three identical upbeat
    headlines and four always-positive live signals for all 36 names), which left the matrix's
    Value Traps and Overrated Leaders quadrants permanently empty and gave the engine nothing to
    disagree with. Roughly 60/25/15 — an ESG-improver basket that still contains names going the
    wrong way, because catching those is the entire product claim."""
    r = _rng(name, "traj")
    return "deteriorating" if r < 0.15 else "mixed" if r < 0.40 else "improving"


def momentum(name, breakdown, traj=None):
    """Illustrative pillar momentum (%), keyed to the pillar scores, the company's trajectory
    and seeded jitter. Deteriorating names tilt AGAINST their pillar score, so a well-rated
    company can be sliding — which is exactly the Overrated Leaders quadrant."""
    traj = traj or trajectory(name)
    tilt, lo, hi = {"improving": (0.5, -4, 12), "mixed": (0.2, -10, 10),
                    "deteriorating": (-0.15, -20, 2)}[traj]

    def mom(score, salt):
        return int(round((score - 50) * tilt + _pick(name, salt, lo, hi)))

    ai = {"improving": (6, 34), "mixed": (-6, 16), "deteriorating": (-26, -2)}[traj]
    return {"environment": mom(breakdown["e_score"], "E"),
            "social": mom(breakdown["s_score"], "S"),
            "governance": mom(breakdown["g_score"], "G"),
            "digital_ai": int(round(_pick(name, "AI", *ai)))}


def live_signals(name, traj=None):
    """Live-signal block matching the company's trajectory. Values may be NEGATIVE — a falling
    carbon-disclosure or AI-hiring number is a real signal, and the engine reads its sign."""
    traj = traj or trajectory(name)
    if traj == "improving":
        return {"ai_hiring_surge": f"+{int(_pick(name,'h',60,360))}%",
                "board_ai_policy": _rng(name, "p") > 0.35,
                "carbon_disclosure": f"+{int(_pick(name,'c',4,22))}%",
                "green_patents": f"+{int(_pick(name,'gp',20,95))}%",
                "controversy_flags": 0 if _rng(name, "f") > 0.15 else 1}
    if traj == "mixed":
        return {"ai_hiring_surge": f"+{int(_pick(name,'h',10,90))}%",
                "board_ai_policy": _rng(name, "p") > 0.6,
                "carbon_disclosure": f"{int(_pick(name,'c',-6,9)):+d}%",
                "green_patents": f"{int(_pick(name,'gp',-10,30)):+d}%",
                "controversy_flags": 0 if _rng(name, "f") > 0.45 else 1}
    return {"ai_hiring_surge": f"{int(_pick(name,'h',-45,-4)):+d}%",
            "board_ai_policy": False,
            "carbon_disclosure": f"{int(_pick(name,'c',-24,-3)):+d}%",
            "green_patents": f"{int(_pick(name,'gp',-30,4)):+d}%",
            "controversy_flags": 1 if _rng(name, "f") > 0.4 else 2}


def market(name, exchange):
    ccy = _CCY.get(exchange, "USD")
    price = round(_pick(name, "px", 4, 40), 2)
    prev_close = round(price * (1 + _pick(name, "pc", -0.02, 0.02)), 2)
    open_ = round(price * (1 + _pick(name, "o", -0.01, 0.01)), 2)
    hi = round(max(price, open_, prev_close) * (1 + _pick(name, "hi", 0.002, 0.02)), 2)
    lo = round(min(price, open_, prev_close) * (1 - _pick(name, "lo", 0.002, 0.02)), 2)
    return {"currency": ccy, "price": price,
            "open": open_, "high": hi, "low": lo, "prev_close": prev_close,
            "market_cap": f"{ccy} {round(_pick(name,'mc',2,90),1)}B",
            "pe_ratio": round(_pick(name, "pe", 8, 22), 1),
            "dividend_yield": f"{round(_pick(name,'dy',1,6),1)}%",
            "week52_high": round(hi * (1 + _pick(name, "wh", 0.05, 0.25)), 2),
            "week52_low": round(lo * (1 - _pick(name, "wl", 0.05, 0.25)), 2),
            "as_of": "2026-01-15"}


# --------------------------------------------------------------------------- #
#  HEADLINE POOLS
# --------------------------------------------------------------------------- #
# Every demo name used to get the SAME three headlines for its trajectory, with only the company
# name swapped in, all dated the same three days. Open two companies side by side in a demo and
# the prop falls over.
#
# These pools keep the polarity fixed per trajectory — the engine reads this wording and turns it
# into directional signals, so an improver must not be handed a controversy — but vary which
# evidence family each name's story is told through. One company's improvement shows up as green
# finance, another's as board oversight, another's as AI-governance hiring. That is closer to how
# a real evidence trail looks, and it exercises more of the taxonomy on screen.
_HEADLINES = {
    "improving": [
        "{n} lifts sustainable-finance disclosure",
        "{n} expands renewable-energy sourcing plan",
        "{n} names sustainability & AI-governance lead",
        "{n} publishes its first externally assured sustainability report",
        "{n} prices a sustainability-linked loan for its transition capex",
        "{n} strengthens board oversight of climate risk",
        "{n} sets a scope 3 emissions reduction target",
        "{n} adds independent directors and a standing audit committee",
    ],
    "mixed": [
        "{n} reports flat emissions intensity for a second year",
        "{n} delays its renewable-energy sourcing milestone",
        "{n} names sustainability & AI-governance lead",
        "{n} keeps its disclosure scope unchanged year on year",
        "{n} restates prior-year figures in its integrated report",
        "{n} defers a decision on its transition capex plan",
        "{n} reports mixed progress against its interim targets",
        "{n} maintains its index membership without improving its score",
    ],
    "deteriorating": [
        "{n} faces a regulatory investigation over effluent discharge",
        "{n} misses its emissions reduction target as disclosure slips",
        "{n} loses its head of sustainability amid restructuring",
        "{n} is fined over a workplace safety incident",
        "{n} discloses a data breach affecting customer records",
        "{n} faces a lawsuit over alleged greenwashing in its marketing",
        "{n} reports a rising lost-time injury rate",
        "{n} is placed under investigation after a supplier audit",
    ],
}

# One sector-flavoured headline per company, so a bank's news reads like a bank's. Same polarity
# discipline as the general pool.
_SECTOR_HEADLINES = {
    "Banks": {
        "improving": ["{n} launches a green loan book for SME borrowers",
                      "{n} extends financial inclusion lending in rural branches"],
        "mixed": ["{n} holds its green financing target flat for the year",
                  "{n} reports no change to its coal exposure policy"],
        "deteriorating": ["{n} is probed over anti-money-laundering controls",
                          "{n} faces a penalty over mis-sold investment products"],
    },
    "Telecom": {
        "improving": ["{n} commits its network to renewable power",
                      "{n} files patents covering network energy efficiency"],
        "mixed": ["{n} reports flat network energy intensity",
                  "{n} keeps its tower electrification plan under review"],
        "deteriorating": ["{n} discloses an outage affecting subscriber data",
                          "{n} faces a regulatory probe over personal data protection"],
    },
    "Power & Renewables": {
        "improving": ["{n} brings a new solar capacity block online",
                      "{n} agrees an early coal retirement under a transition mechanism"],
        "mixed": ["{n} pushes back the commissioning date on a wind project",
                  "{n} reports unchanged generation mix year on year"],
        "deteriorating": ["{n} extends the life of a coal-fired plant",
                          "{n} is investigated over an ash pond discharge"],
    },
    "Consumer Staples": {
        "improving": ["{n} expands smallholder training across its supply chain",
                      "{n} publishes a traceability report for its sourcing"],
        "mixed": ["{n} reports partial traceability across its supply base",
                  "{n} leaves its packaging targets unchanged"],
        "deteriorating": ["{n} faces a forced labour finding at a supplier site",
                          "{n} is fined over effluent discharge at a processing plant"],
    },
    "Real Estate": {
        "improving": ["{n} certifies a data centre asset to a green building standard",
                      "{n} issues a green bond against its logistics portfolio"],
        "mixed": ["{n} reports flat portfolio energy intensity",
                  "{n} defers retrofit capex on two older assets"],
        "deteriorating": ["{n} reports a fatality at a construction site",
                          "{n} faces an investigation over building safety compliance"],
    },
}


def _sector_key(sector):
    """Our sector strings are ``GICS — sub-industry``; the pools are keyed on the sub-industry."""
    return (sector or "").split("—")[-1].strip()


def news(name, traj=None, sector=None):
    """Three dated illustrative headlines that MATCH the company's trajectory.

    No URLs are ever emitted and every source is labelled illustrative (HARD RULE 2): these are
    props for a fictional company, and the engine reads their wording, so an all-positive set
    would have made every demo name look like an improver regardless of its numbers.

    Composition is one sector-flavoured headline plus two from the general pool for the same
    trajectory, chosen by a seeded hash of the name so the file never churns between runs. Dates
    are per-company too — three shared dates across all 36 names was the other tell.
    """
    traj = traj or trajectory(name)
    pool = _HEADLINES[traj]
    sector_pool = _SECTOR_HEADLINES.get(_sector_key(sector), {}).get(traj, [])

    picks = []
    if sector_pool:
        picks.append(sector_pool[int(_rng(name, "sh") * len(sector_pool)) % len(sector_pool)])
    # Walk the general pool from a seeded offset with a coprime stride, so two names with
    # adjacent hashes do not land on the same pair.
    start = int(_rng(name, "h0") * len(pool))
    stride = 3 if len(pool) % 3 else 5
    i = 0
    while len(picks) < 3 and i < len(pool):
        cand = pool[(start + i * stride) % len(pool)]
        if cand not in picks:
            picks.append(cand)
        i += 1

    # Newest headline 4-38 days before the demo as-of, then two more spaced 18-46 days apart.
    day0 = int(_pick(name, "d0", 4, 38))
    gap1 = int(_pick(name, "d1", 18, 46))
    gap2 = int(_pick(name, "d2", 18, 46))
    dates = [_date_back(d) for d in (day0, day0 + gap1, day0 + gap1 + gap2)]

    src = ["DemoWire (illustrative)", "Mock Business Daily (illustrative)",
           "ASEAN ESG Demo (illustrative)"]
    return [{"title": picks[i].format(n=name), "source": src[i], "date": dates[i]}
            for i in range(3)]


def analyst_coverage(name):
    return {"analysts": int(_pick(name, "an", 6, 28)), "as_of": "Q1 2026"}


def price_change_90d(name):
    v = round(_pick(name, "p90", -8, 14), 1)
    return f"{'+' if v >= 0 else ''}{v}%"
